# Generated by Django 5.0.3 on 2024-10-23 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_librarymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('borrowed_by', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=10)),
                ('borrowed_date', models.DateField(default=django.utils.timezone.now)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('overdue', 'Overdue'), ('returned', 'Returned')], default='overdue', max_length=10)),
            ],
        ),
    ]
