# Generated by Django 5.0.3 on 2024-10-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_borrowedbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
    ]
